sonar.projectKey=gate-security
sonar.projectName=gate security
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_df055f74b3580071254afdd873fef2eaae491fe5
