import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../../common/config/theme';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContainer: {
    paddingBottom: 120,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerTitle: {
    fontSize: 24,
    color: COLORS.primary,
    fontFamily: FONTS.inter,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  headerActionBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  searchContainer: {
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  filterCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    paddingHorizontal: 12,
    height: 46,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: FONTS.inter,
    color: COLORS.secondary,
    paddingVertical: 0,
  },
  dateFilterContainer: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  dateCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    paddingVertical: 6,
    height: 48,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  dateCardActive: {
    borderColor: COLORS.primary,
  },
  dateIconContainer: {
    marginRight: 6,
  },
  dateLabelContainer: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 9,
    color: COLORS.muted,
    fontFamily: FONTS.inter,
  },
  dateValue: {
    fontSize: 12,
    color: COLORS.secondary,
    fontFamily: FONTS.inter,
    marginTop: -1,
  },
  dateSeparatorText: {
    marginHorizontal: 8,
    fontSize: 12,
    color: COLORS.muted,
    fontFamily: FONTS.inter,
  },
  typeContainer: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  typeLabel: {
    fontSize: 11,
    fontFamily: FONTS.inter,
    color: COLORS.muted,
    marginBottom: 8,
  },
  typeChipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  typeChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  typeChipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  typeChipText: {
    fontSize: 12,
    fontFamily: FONTS.inter,
    color: COLORS.muted,
  },
  typeChipTextActive: {
    color: '#FFFFFF',
  },
  tabContainer: {
    marginHorizontal: 16,
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  activeTabButton: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  tabText: {
    fontSize: 12,
    color: COLORS.muted,
    fontFamily: FONTS.inter,
  },
  activeTabText: {
    color: COLORS.primary,
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 20,
  },
  statsCardRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    gap: 6,
    marginBottom: 16,
  },
  statsCardSingle: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ECEFF1',
    padding: 8,
    elevation: 2,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    justifyContent: 'space-between',
  },
  statsCardLabel: {
    fontSize: 13,
    color: '#64748B',
    fontFamily: FONTS.inter,
    marginBottom: 6,
  },
  statsCardMiddleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  statsCardIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statsCardTextCol: {
    flex: 1,
  },
  statsCardValue: {
    fontSize: 18,
    fontFamily: FONTS.inter,
  },
  statsCardLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#EFF6FF',
    borderRadius: 8,
    paddingVertical: 6,
    marginTop: 8,
  },
  statsCardLinkText: {
    fontSize: 10,
    color: '#1A73E8',
    fontFamily: FONTS.inter,
  },
  statsCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  statsIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  statsLabel: {
    fontSize: 9,
    color: COLORS.muted,
    fontFamily: FONTS.inter,
    marginBottom: 1,
  },
  statsValue: {
    fontSize: 18,
    color: COLORS.secondary,
    fontFamily: FONTS.inter,
    marginBottom: 4,
  },
  statsLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statsLinkText: {
    fontSize: 10,
    color: COLORS.primary,
    fontFamily: FONTS.inter,
    marginRight: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 10,
    marginBottom: 8,
  },
  sectionHeaderText: {
    fontSize: 13,
    fontFamily: FONTS.inter,
    color: COLORS.secondary,
  },
  sectionHeaderBadge: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  sectionHeaderBadgeText: {
    fontSize: 11,
    fontFamily: FONTS.inter,
    color: '#334155',
  },
  card: {
    position: 'relative',
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderLeftWidth: 4,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  cardLeftCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  cardLeftCircleText: {
    fontSize: 11,
    fontFamily: FONTS.inter,
  },
  cardMiddle: {
    flex: 1,
  },
  cardRow1: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    marginBottom: 4,
  },
  cardPlateNumber: {
    fontSize: 14,
    fontFamily: FONTS.inter,
    color: COLORS.secondary,
    marginRight: 2,
  },
  badgeService: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  badgeServiceText: {
    fontSize: 10,
    fontFamily: FONTS.inter,
    color: COLORS.primary,
  },
  badgeVisitor: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  badgeVisitorText: {
    fontSize: 10,
    fontFamily: FONTS.inter,
    color: '#64748B',
  },
  badgePickup: {
    backgroundColor: '#F5F3FF',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  badgePickupText: {
    fontSize: 10,
    fontFamily: FONTS.inter,
    color: '#8B5CF6',
  },
  badgeEnquiry: {
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  badgeEnquiryText: {
    fontSize: 10,
    fontFamily: FONTS.inter,
    color: '#D97706',
  },
  badgeEntry: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  badgeEntryText: {
    fontSize: 10,
    fontFamily: FONTS.inter,
    color: '#10B981',
  },
  badgeExit: {
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  badgeExitText: {
    fontSize: 10,
    fontFamily: FONTS.inter,
    color: '#EF4444',
  },
  cardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  cardInfoText: {
    fontSize: 12,
    fontFamily: FONTS.inter,
    color: COLORS.secondary,
  },
  cardSubInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardSubInfoText: {
    fontSize: 11,
    fontFamily: FONTS.inter,
    color: COLORS.muted,
  },
  cardRightChevron: {
    marginLeft: 8,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 13,
    color: COLORS.muted,
    fontFamily: FONTS.inter,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  bottomSheetContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 36 : 24,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 18,
    color: COLORS.secondary,
    fontFamily: FONTS.inter,
  },
  sheetCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyBtn: {
    flex: 1,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: FONTS.inter,
  },
  sheetButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  resetBtn: {
    flex: 1,
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  resetBtnText: {
    color: '#64748B',
    fontSize: 15,
    fontFamily: FONTS.inter,
  },
  skeletonCardLeftCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  skeletonRow1: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
    alignItems: 'center',
  },
  skeletonPlate: {
    width: 90,
    height: 16,
    borderRadius: 4,
  },
  skeletonBadge: {
    width: 50,
    height: 14,
    borderRadius: 4,
  },
  skeletonRow2: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    marginBottom: 4,
  },
  skeletonRow3: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  skeletonText1: {
    width: 120,
    height: 12,
    borderRadius: 3,
  },
  skeletonText2: {
    width: 150,
    height: 12,
    borderRadius: 3,
  },
  skeletonChevron: {
    width: 12,
    height: 20,
    borderRadius: 2,
  },
  skeletonContainer: {
    gap: 10,
    marginTop: 10,
  },
});
