import { StyleSheet } from 'react-native';
import { colors, fonts, spacing, radius } from './theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: 120,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 60,
    paddingHorizontal: spacing.sm,
  },
  headerTitle: {
    fontFamily: fonts.inter,
    fontSize: 22,
    fontWeight: '700',
    color: colors.primary,
  },
  profileCard: {
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  editProfileButton: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: colors.shadowHeavy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#EEF2F6',
    zIndex: 10,
  },
  avatarContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  avatarText: {
    fontFamily: fonts.inter,
    fontSize: 32,
    color: colors.primaryDeep,
  },
  profileDetails: {
    alignItems: 'center',
    gap: 4,
  },
  profileName: {
    fontFamily: fonts.inter,
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  profileRole: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.mutedText,
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacing.sm,
  },
  contactInfo: {
    width: '100%',
    gap: spacing.md,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  contactRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldLabel: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.mutedText,
  },
  fieldValue: {
    fontFamily: fonts.inter,
    fontSize: 16,
    color: colors.text,
  },
  editInput: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontSize: 14,
    color: colors.text,
    fontFamily: fonts.inter,
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  editPencilBtn: {
    padding: 4,
  },
  editButtonRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
    marginTop: spacing.md,
  },
  menuSection: {
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  logoutButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoutText: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.danger,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 18, 30, 0.4)',
  },
  modalCard: {
    backgroundColor: colors.surface,
    width: '85%',
    maxWidth: 340,
    borderRadius: radius.lg,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  modalTitle: {
    fontFamily: fonts.inter,
    fontSize: 18,
    color: colors.text,
    marginBottom: 10,
  },
  modalMessage: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.mutedText,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 18,
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  errorBorder: {
    borderColor: colors.danger,
  },
  errorText: {
    fontFamily: fonts.inter,
    fontSize: 11,
    color: colors.danger,
    marginTop: 4,
    marginLeft: 4,
  },
});

export default styles;
