import { StyleSheet } from 'react-native';
import { COLORS } from '../config/theme';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  container: { flex: 1 },
  headerGradient: { height: 180, backgroundColor: COLORS.primary, position: 'absolute', top: 0, left: 0, right: 0 },
  profileHeader: { flexDirection: 'row', alignItems: 'center', marginTop: 40, marginBottom: 24, paddingHorizontal: 20, gap: 18 },
  avatarLarge: { width: 85, height: 85, borderRadius: 24, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: 'rgba(255,255,255,0.4)', elevation: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 4 },
  avatarText: { color: COLORS.primary, fontSize: 28, },
  statusDot: { position: 'absolute', bottom: -4, right: -4, width: 22, height: 22, borderRadius: 11, backgroundColor: '#22C55E', borderWidth: 3, borderColor: '#FFFFFF' },
  headerInfo: { flex: 1, justifyContent: 'center' },
  staffName: { color: '#FFFFFF', fontSize: 22, },
  staffId: { color: 'rgba(255,255,255,0.8)', fontSize: 13, marginTop: 2 },
  tagContainer: { marginTop: 8, alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  tagText: { color: '#FFFFFF', fontSize: 10, textTransform: 'uppercase' },
  menuSection: { paddingHorizontal: 16, marginBottom: 24 },
  sectionTitle: { color: COLORS.secondary, fontSize: 16, marginBottom: 12, marginLeft: 4 },
  menuCard: { backgroundColor: COLORS.card, borderRadius: 20, borderWidth: 1, borderColor: COLORS.border, overflow: 'hidden' },
  menuItem: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  menuIconContainer: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#F8FAFC', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  menuLabel: { flex: 1, color: COLORS.secondary, fontSize: 14, },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginHorizontal: 16, padding: 16, borderRadius: 18, backgroundColor: '#FEF2F2', marginBottom: 40, gap: 10 },
  logoutBtnText: { color: '#EF4444', fontSize: 15, },
  statsRow: { flexDirection: 'row', backgroundColor: '#FFFFFF', marginHorizontal: 16, borderRadius: 22, paddingVertical: 20, borderWidth: 1, borderColor: COLORS.border, marginBottom: 24, elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 3 },
  statItem: { flex: 1, alignItems: 'center' },
  statBorder: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: '#F1F5F9' },
  statValue: { color: COLORS.primary, fontSize: 18, },
  statLabel: { color: COLORS.muted, fontSize: 10, textTransform: 'uppercase', marginTop: 4 },
});
