import { StyleSheet } from 'react-native';
import { COLORS } from '../config/theme';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  container: { flexGrow: 1, padding: 16, paddingBottom: 28 },
  headerCard: { backgroundColor: COLORS.card, borderRadius: 22, padding: 16, borderWidth: 1, borderColor: COLORS.border, marginBottom: 14 },
  title: { color: COLORS.secondary, fontSize: 20},
  subtitle: { color: COLORS.muted, fontSize: 12, marginTop: 4 },
  sectionCard: { backgroundColor: COLORS.card, borderRadius: 20, padding: 14, borderWidth: 1, borderColor: COLORS.border, marginBottom: 12 },
  sectionTitle: { color: COLORS.secondary, fontSize: 15, marginBottom: 8 },
  dateTimeRow: { flexDirection: 'row', backgroundColor: '#F8FAFC', borderRadius: 12, padding: 10, gap: 16 },
  dateTimeItem: { flex: 1 },
  dateTimeLabel: { color: COLORS.muted, fontSize: 10, marginBottom: 2, textTransform: 'uppercase' },
  dateTimeValue: { color: COLORS.secondary, fontSize: 14},
  photoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  countBadge: { backgroundColor: '#F1F5F9', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  countText: { color: COLORS.primary, fontSize: 12, },
  addPhotoSection: { alignItems: 'center', marginBottom: 16 },
  addPhotoSlotLarge: { width: '100%', height: 100, backgroundColor: '#F8FAFC', borderRadius: 18, borderStyle: 'dashed', borderWidth: 2, borderColor: COLORS.primary, justifyContent: 'center', alignItems: 'center' },
  addCircleLarge: { width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  addSymbolLarge: { color: '#FFFFFF', fontSize: 28,  },  
  addPhotoLabelLarge: { color: COLORS.primary, fontSize: 13, letterSpacing: 0.5 },
  previewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10, borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: 16 },
  photoThumbContainer: { width: 85, height: 85, position: 'relative' },
  photoThumb: { width: 85, height: 85, backgroundColor: '#F1F5F9', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, overflow: 'hidden' },
  deleteBadge: { position: 'absolute', top: -6, right: -6, backgroundColor: '#EF4444', width: 24, height: 24, borderRadius: 12, justifyContent: 'center', alignItems: 'center', elevation: 3, zIndex: 1 },
  deleteText: { color: '#FFFFFF', fontSize: 16, lineHeight: 20 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tag: { borderWidth: 1, borderColor: COLORS.border, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8, marginRight: 8, marginBottom: 8 },
  tagText: { color: COLORS.secondary, fontSize: 12},
  input: { height: 48, backgroundColor: COLORS.background, borderRadius: 14, paddingHorizontal: 12, color: COLORS.secondary, borderWidth: 1, borderColor: COLORS.border},
  inputActionRow: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  fetchButton: { backgroundColor: COLORS.primary, height: 48, borderRadius: 14, paddingHorizontal: 20, justifyContent: 'center', alignItems: 'center', elevation: 2 },
  fetchButtonText: { color: '#FFFFFF', fontSize: 13, letterSpacing: 1 },
  textarea: { minHeight: 80, backgroundColor: COLORS.background, borderRadius: 14, padding: 10, color: COLORS.secondary, textAlignVertical: 'top' },
  actionRow: { flexDirection: 'row', gap: 10 },
});
