import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../common/styles/theme';
import Fonts from '../../common/assets/fonts/FontStyle';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 60,
    paddingHorizontal: spacing.sm,
  },
  headerTitleContainer: {
    flex: 1,
    minWidth: 200,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  headerTitle: {
    fontFamily: Fonts.inter,
    fontSize: 22,
    fontWeight: '700',
    color: colors.primary,
  },
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: colors.shadowHeavy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#EEF2F6',
  },
  notificationBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontFamily: Fonts.inter,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginHorizontal: 4,
    marginBottom: 2,
  },
  statsCardTotal: {
    flex: 1,
    backgroundColor: '#EEF2F6',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  statsCardWaiting: {
    flex: 1,
    backgroundColor: '#FFFBEB',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#FDE68A',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  statsCardActive: {
    flex: 1,
    backgroundColor: '#F0FDFA',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#CCFBF1',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  statsInfoGroup: {
    flex: 1,
    gap: 2,
  },
  statsValue: {
    fontFamily: Fonts.inter,
    fontSize: 20,
    color: colors.text,
  },
  statsLabel: {
    fontFamily: Fonts.inter,
    fontSize: 9,
    color: colors.mutedText,
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  statsIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  listCard: {
    flex: 1,
    padding: spacing.sm,
  },
  searchContainer: {
    marginBottom: spacing.sm,
  },
  searchBar: {
    minHeight: 40,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    gap: spacing.xs,
  },
  searchInput: {
    flex: 1,
    fontFamily: Fonts.inter,
    color: colors.text,
    paddingVertical: 4,
    fontSize: 13,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.sm,
    marginTop: 40,
  },
  emptyIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  emptyTitle: {
    fontFamily: Fonts.inter,
    fontSize: 15,
    color: colors.text,
  },
  emptySubtitle: {
    fontFamily: Fonts.inter,
    fontSize: 12,
    color: colors.mutedText,
    textAlign: 'center',
    maxWidth: 240,
    lineHeight: 18,
  },
  tabletCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    margin: 4,
    flex: 1 / 3,
    maxWidth: '32%',
    gap: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  tabletCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  entryBadge: {
    borderRadius: radius.pill,
    paddingVertical: 2,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  entryBadgeDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  entryBadgeText: {
    fontFamily: Fonts.inter,
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  waitingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  waitingText: {
    fontFamily: Fonts.inter,
    fontSize: 10,
  },
  waitingBold: {
    fontFamily: Fonts.inter,
  },
  plateContainerTablet: {
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 6,
    backgroundColor: '#EFF6FF',
    paddingVertical: 5,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginVertical: 2,
  },
  plateTextTablet: {
    fontFamily: Fonts.inter,
    fontSize: 14,
    color: '#2563EB',
    letterSpacing: 0.5,
  },
  actionButtonTablet: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: radius.md,
    paddingVertical: 8,
    minHeight: 36,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  actionButtonTextTablet: {
    color: '#FFFFFF',
    fontFamily: Fonts.inter,
    fontSize: 12,
  },
  mobileRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  mobileLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  plateContainerMobile: {
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 6,
    backgroundColor: '#EFF6FF',
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  plateTextMobile: {
    fontFamily: Fonts.inter,
    fontSize: 11.5,
    color: '#2563EB',
    letterSpacing: 0.5,
  },
  mobileMiddleInfo: {
    gap: 2,
    flex: 1,
  },
  entryBadgeMobile: {
    borderRadius: radius.pill,
    paddingVertical: 1.5,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    alignSelf: 'flex-start',
  },
  entryBadgeDotMobile: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
  },
  entryBadgeTextMobile: {
    fontFamily: Fonts.inter,
    fontSize: 7.5,
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  waitingBadgeMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginLeft: 1,
  },
  waitingTextMobile: {
    fontFamily: Fonts.inter,
    fontSize: 9,
  },
  waitingBoldMobile: {
    fontFamily: Fonts.inter,
  },
  actionButtonMobile: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.18,
    shadowRadius: 3,
    elevation: 2,
    marginLeft: 6,
  },
  actionButtonTextMobile: {
    color: '#FFFFFF',
    fontFamily: Fonts.inter,
    fontSize: 10.5,
  },
  footerLoader: {
    paddingVertical: 12,
    alignItems: 'center',
  },
});

export default styles;
