import { StyleSheet } from 'react-native';
import { colors, fonts, radius, spacing } from '../../common/styles/theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 56,
    paddingHorizontal: spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerTitle: {
    fontFamily: fonts.inter,
    fontSize: 17,
    color: colors.text,
  },
  scrollContent: {
    padding: spacing.md,
    gap: spacing.sm,
    flexGrow: 1,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 80,
  },
  emptyCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  emptyTitle: {
    fontFamily: fonts.inter,
    fontSize: 16,
    color: colors.text,
    marginBottom: 4,
  },
  emptySubtitle: {
    fontFamily: fonts.inter,
    fontSize: 12.5,
    color: colors.mutedText,
    textAlign: 'center',
    maxWidth: 240,
    lineHeight: 18,
  },
  notificationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: spacing.sm,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1.5,
    marginBottom: spacing.xs,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  iconCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  vehicleNumber: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.text,
  },
  serviceBadge: {
    backgroundColor: '#F1F5F9',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  serviceText: {
    fontFamily: fonts.inter,
    fontSize: 9.5,
    color: '#475569',
    textTransform: 'uppercase',
  },
  waitingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  waitingLabel: {
    fontFamily: fonts.inter,
    fontSize: 12,
  },
  cardBody: {
    paddingVertical: 2,
  },
  messageText: {
    fontFamily: fonts.inter,
    fontSize: 12.5,
    color: colors.mutedText,
  },
  actionButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  actionButtonText: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: '#FFFFFF',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: radius.md,
    padding: 4,
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  activeTabButton: {
    backgroundColor: '#FFFFFF',
    borderColor: colors.border,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  tabButtonText: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.mutedText,
    fontWeight: '500',
  },
  activeTabButtonText: {
    color: colors.primary,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    padding: spacing.lg,
    width: '90%',
    maxWidth: 340,
    alignItems: 'center',
    shadowColor: colors.shadowHeavy,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    fontFamily: fonts.inter,
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  modalMessage: {
    fontFamily: fonts.inter,
    fontSize: 13.5,
    color: colors.mutedText,
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  modalButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 10,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  modalButtonText: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  modalIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E5F7EE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  modalInfoContainer: {
    alignSelf: 'stretch',
    backgroundColor: '#F8FAFC',
    borderRadius: radius.md,
    padding: spacing.md,
    marginVertical: spacing.md,
    gap: spacing.xs,
  },
  modalInfoLabel: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.mutedText,
  },
  modalInfoValue: {
    fontWeight: '600',
    color: colors.text,
  },
  customerMobileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  customerMobileText: {
    fontFamily: fonts.inter,
    fontSize: 12.5,
    color: colors.mutedText,
  },
});

export default styles;
