import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../common/styles/theme';
import Fonts from '../../common/assets/fonts/FontStyle';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F7FB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 60,
    paddingHorizontal: spacing.md,
    backgroundColor: 'transparent',
    paddingBottom: 8,
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 140,
    backgroundColor: 'transparent',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: colors.shadowHeavy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#EEF2F6',
  },
  headerTitle: {
    fontFamily: Fonts.inter,
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
  },
  scrollContent: {
    padding: spacing.md,
    gap: spacing.lg,
    paddingBottom: 120,
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginTop: 10,
    elevation: 6,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  avatarCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  avatarText: {
    fontFamily: Fonts.inter,
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
  },
  heroMeta: {
    flex: 1,
    gap: 3,
  },
  ownerName: {
    fontFamily: Fonts.inter,
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  vehicleSubtitle: {
    fontFamily: Fonts.inter,
    fontSize: 12,
    color: colors.mutedText,
    fontWeight: '500',
  },
  plateBadge: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 15, 126, 0.2)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  plateText: {
    fontFamily: Fonts.inter,
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 1,
  },
  heroDivider: {
    height: 1,
    backgroundColor: '#EEF2F6',
    marginVertical: spacing.md,
  },
  heroFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 10,
    borderRadius: radius.md,
  },
  footerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  footerItemText: {
    fontFamily: Fonts.inter,
    fontSize: 12.5,
    fontWeight: '500',
    color: colors.primaryDeep,
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    padding: spacing.md,
    gap: spacing.md,
    elevation: 3,
    shadowColor: colors.shadowHeavy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontFamily: Fonts.inter,
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  contactRow: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.xs,
  },
  contactDetail: {
    flex: 1,
  },
  contactLabel: {
    fontFamily: Fonts.inter,
    fontSize: 11,
    fontWeight: '600',
    color: colors.mutedText,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  contactValue: {
    fontFamily: Fonts.inter,
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
  },
  specGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  gridCell: {
    width: '47%',
    margin: '1.5%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: colors.primarySoft,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    minHeight: 56,
    justifyContent: 'center',
  },
  cellLabel: {
    fontFamily: Fonts.inter,
    fontSize: 10.5,
    fontWeight: '600',
    color: colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cellValue: {
    fontFamily: Fonts.inter,
    fontSize: 13.5,
    fontWeight: '500',
    color: colors.text,
    marginTop: 4,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: colors.primarySoft,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  columnTitle: {
    fontFamily: Fonts.inter,
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  columnValue: {
    fontFamily: Fonts.inter,
    fontSize: 13,
    fontWeight: '500',
    color: colors.text,
  },
  calculationSection: {
    marginTop: spacing.sm,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.primarySoft,
  },
  calcRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calcLabel: {
    fontFamily: Fonts.inter,
    fontSize: 13,
    fontWeight: '500',
    color: colors.mutedText,
  },
  calcValue: {
    fontFamily: Fonts.inter,
    fontSize: 13.5,
    fontWeight: '600',
    color: colors.text,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
    padding: 16,
    backgroundColor: colors.primarySoft,
    borderRadius: 10,
    elevation: 1,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  totalLabel: {
    fontFamily: Fonts.inter,
    fontSize: 14,
    color: colors.primaryDeep,
  },
  totalValue: {
    fontFamily: Fonts.inter,
    fontSize: 18,
    color: colors.primaryDeep,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  photoFrame: {
    width: '48%',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    padding: 6,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.primarySoft,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  photoFrameTitle: {
    fontFamily: Fonts.inter,
    fontSize: 11.5,
    fontWeight: '600',
    color: colors.primaryDeep,
    marginTop: 6,
    marginBottom: 2,
  },
});

export default styles;
