import { StyleSheet } from 'react-native';
import { colors, fonts, radius, spacing } from '../../common/styles/theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 12,
    marginTop: 8,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  headerTitle: {
    fontFamily: fonts.inter,
    fontSize: 22,
    color: colors.primary,
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginHorizontal: 4,
    marginBottom: 2,
  },
  statsCardTotal: {
    flex: 1,
    backgroundColor: '#EEF2F6',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  statsCardActive: {
    flex: 1,
    backgroundColor: '#FFFBEB',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#FDE68A',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  statsCardCompleted: {
    flex: 1,
    backgroundColor: '#F0FDFA',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#CCFBF1',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  statsInfoGroup: {
    flex: 1,
    gap: 2,
  },
  statsValue: {
    fontFamily: fonts.inter,
    fontSize: 20,
    color: colors.text,
  },
  statsLabel: {
    fontFamily: fonts.inter,
    fontSize: 9,
    color: colors.mutedText,
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  statsIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  listCard: {
    flex: 1,
    padding: spacing.sm,
  },
  searchContainer: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  searchBar: {
    flex: 1,
    minHeight: 40,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    gap: spacing.xs,
  },
  searchInput: {
    flex: 1,
    fontFamily: fonts.inter,
    color: colors.text,
    paddingVertical: 4,
    fontSize: 13,
  },
  filterButton: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeFilterIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  filterButtonPrimary: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  filterButtonPrimaryActive: {
    borderColor: '#93C5FD',
    borderWidth: 2,
  },
  filterIndicatorPrimary: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
  },
  searchContainerMain: {
    marginBottom: 16,
  },
  searchBarPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
  },
  searchInputPrimary: {
    flex: 1,
    fontFamily: fonts.inter,
    fontSize: 15,
    color: colors.text,
    marginLeft: 12,
    paddingVertical: 8,
  },
  searchClearButtonPrimary: {
    padding: 4,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
  },
  tabButtonActive: {
    backgroundColor: colors.primary,
  },
  tabButtonInactive: {
    backgroundColor: 'transparent',
  },
  tabButtonText: {
    fontFamily: fonts.inter,
    fontSize: 14,
  },
  tabButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  tabButtonTextInactive: {
    color: colors.text,
    fontWeight: '500',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.sm,
    marginTop: 40,
  },
  emptyIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  emptyTitle: {
    fontFamily: fonts.inter,
    fontSize: 15,
    color: colors.text,
  },
  emptySubtitle: {
    fontFamily: fonts.inter,
    fontSize: 12,
    color: colors.mutedText,
    textAlign: 'center',
    maxWidth: 240,
    lineHeight: 18,
  },
  itemCardMain: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 12,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 12,
  },
  cardAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E5F7EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardAvatarText: {
    fontFamily: fonts.inter,
    fontSize: 18,
    fontWeight: '600',
    color: '#1F8E57',
  },
  cardInfoContainer: {
    flex: 1,
    gap: 6,
  },
  cardRowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontFamily: fonts.inter,
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  cardPlateBadge: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  cardPlateText: {
    fontFamily: fonts.inter,
    fontSize: 12,
    fontWeight: '600',
    color: '#3B82F6',
  },
  cardSpecs: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: '#64748B',
  },
  cardDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  cardDateText: {
    fontFamily: fonts.inter,
    fontSize: 12,
    color: '#94A3B8',
  },
  cardServicesBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  cardServicesText: {
    fontFamily: fonts.inter,
    fontSize: 12,
    fontWeight: '600',
    color: '#4F46E5',
  },
  cardChevronContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    padding: spacing.lg,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalTitle: {
    fontFamily: fonts.inter,
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateInputsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  dateInputButton: {
    flex: 1,
    height: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing.sm,
    justifyContent: 'center',
  },
  dateInputLabel: {
    fontFamily: fonts.inter,
    fontSize: 11,
    color: colors.mutedText,
    marginBottom: 2,
  },
  dateInputValue: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.text,
  },
  quickSelectRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginVertical: spacing.sm,
  },
  quickSelectChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    borderWidth: 1,
  },
  quickSelectText: {
    fontFamily: fonts.inter,
    fontSize: 11.5,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: spacing.sm,
  },
  calendarNavButton: {
    padding: spacing.xs,
  },
  calendarMonthLabel: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.text,
  },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  calendarWeekText: {
    width: '13%',
    textAlign: 'center',
    fontFamily: fonts.inter,
    fontSize: 11,
    color: colors.mutedText,
  },
  calendarDaysContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  calendarDayCell: {
    width: '13%',
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    borderRadius: 19,
  },
  calendarDayText: {
    fontFamily: fonts.inter,
    fontSize: 12.5,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  resetButton: {
    flex: 1,
    height: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetButtonText: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.text,
  },
  applyButton: {
    flex: 2,
    height: 48,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: '#FFFFFF',
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: spacing.sm,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardFooterLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  footerText: {
    fontFamily: fonts.inter,
    fontSize: 11,
    color: colors.text,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dateText: {
    fontFamily: fonts.inter,
    fontSize: 10,
    color: colors.mutedText,
  },
  activeFiltersContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.xs,
    paddingHorizontal: 4,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterChipText: {
    fontFamily: fonts.inter,
    fontSize: 12,
    color: colors.text,
    fontWeight: '500',
  },
  filterClearButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  jobCardNoText: {
    fontFamily: fonts.inter,
    fontSize: 11,
    marginLeft: 8,
    color: colors.mutedText,
  },
  footerRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  billingAmountText: {
    fontFamily: fonts.inter,
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  statusBadgeReady: {
    backgroundColor: '#ECFDF5',
  },
  statusTextReady: {
    color: '#059669',
  },
  statusBadgeAssigned: {
    backgroundColor: '#FFF7ED',
  },
  statusTextAssigned: {
    color: '#D97706',
  },
  statusBadgeDefault: {
    backgroundColor: '#EFF6FF',
  },
  statusTextDefault: {
    color: '#2563EB',
  },
  statsIconTotal: {
    backgroundColor: 'rgba(15, 92, 150, 0.08)',
  },
  statsIconActive: {
    backgroundColor: 'rgba(217, 119, 6, 0.08)',
  },
  statsIconCompleted: {
    backgroundColor: 'rgba(13, 148, 136, 0.08)',
  },
  clearQueryButton: {
    padding: 4,
  },
});

export default styles;
