import { StyleSheet } from 'react-native';
import { colors, fonts, spacing } from '../../common/styles/theme';

const styles = StyleSheet.create({
  container: {
    gap: spacing.lg,
  },
  selectionSection: {
    gap: spacing.md,
    zIndex: 10,
  },
  sectionTitle: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: '#334155',
    letterSpacing: 0.3,
  },
  dropdownContainer: {
    position: 'relative',
    width: '100%',
    zIndex: 100,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  dropdownButtonText: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.mutedText,
  },
  dropdownList: {
    marginTop: spacing.sm,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    maxHeight: 250,
    overflow: 'hidden',
  },
  dropdownScrollView: {
    flexGrow: 1,
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontFamily: fonts.inter,
    fontSize: 12,
    color: colors.mutedText,
    marginTop: 8,
  },
  emptyDropdownText: {
    padding: 16,
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.mutedText,
    textAlign: 'center',
  },
  catalogItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#FFFFFF',
  },
  catalogItemInfo: {
    flex: 1,
    paddingRight: 8,
  },
  catalogItemName: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.text,
  },
  catalogItemCategory: {
    fontFamily: fonts.inter,
    fontSize: 10,
    color: colors.mutedText,
    marginTop: 2,
  },
  catalogItemPriceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  catalogItemPrice: {
    fontFamily: fonts.inter,
    fontSize: 13,
    color: colors.primary,
  },
  addedBadge: {
    fontSize: 10,
    fontFamily: fonts.inter,
    color: '#0D9488',
    backgroundColor: '#E6F4EA',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  selectedHeaderRow: {
    gap: spacing.md,
    zIndex: 1,
    marginTop: spacing.sm,
  },
  selectedHeaderTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectedTitle: {
    fontFamily: fonts.inter,
    fontSize: 15,
    color: '#334155',
    letterSpacing: 0.3,
  },
  clearAllButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  clearAllText: {
    fontFamily: fonts.inter,
    fontSize: 12,
    color: colors.danger,
  },
  emptySelectedContainer: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    borderRadius: 16,
    padding: spacing.xl,
    backgroundColor: '#F8FAFC',
  },
  emptySelectedTitle: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: '#64748B',
    marginTop: 10,
    textAlign: 'center',
  },
  emptySelectedSubtitle: {
    fontFamily: fonts.inter,
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
    textAlign: 'center',
  },
  selectedItemsList: {
    gap: spacing.md,
  },
  selectedItemsCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1,
  },
  selectedItemRow: {
    padding: 16,
    backgroundColor: '#FFFFFF',
  },
  selectedItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  selectedItemInfo: {
    flex: 1,
    marginRight: 8,
  },
  selectedItemName: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.text,
  },
  selectedItemCategory: {
    fontFamily: fonts.inter,
    fontSize: 11,
    color: colors.mutedText,
    marginTop: 2,
  },
  deleteButton: {
    padding: 4,
  },
  selectedItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  qtyControlsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  qtyButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
  },
  qtyText: {
    fontFamily: fonts.inter,
    fontSize: 14,
    color: colors.text,
    minWidth: 20,
    textAlign: 'center',
  },
  selectedItemPriceInfo: {
    alignItems: 'flex-end',
  },
  selectedItemPrice: {
    fontFamily: fonts.inter,
    fontSize: 15,
    color: colors.primaryDeep,
  },
  selectedItemPriceEach: {
    fontFamily: fonts.inter,
    fontSize: 10,
    color: colors.mutedText,
    marginTop: 1,
  },
  totalCostCard: {
    backgroundColor: colors.primaryDeep,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: colors.primaryDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 3,
  },
  totalCostLabel: {
    color: '#E2E8F6',
    fontFamily: fonts.inter,
    fontSize: 12,
    opacity: 0.9,
  },
  totalCostValue: {
    color: '#FFFFFF',
    fontFamily: fonts.inter,
    fontSize: 24,
    marginTop: 2,
  },
  totalCostIconContainer: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 10,
    padding: 8,
  },
});

export default styles;
